### PR TITLE
Added NSBM 

### PR DESCRIPTION
**Pull request by uvinduperera**
Added NSBM FOSS logo

### CODE REVIEW

**Review by sdglhm — CHANGES_REQUESTED** [review]
Hi,

I can see a duplicate file. Is it a necessary one? If not, could you please remove it?

Thank you

**Comment by uvinduperera** [comment]
Yes there is a difference. We use these three logos depending on the design

**Comment by sdglhm** [comment]
@uvinduperera In that case, can we remove the space in the name? And change 'copy' into something meaningful?

**Comment by uvinduperera** [comment]
Sure I will

**Review by sdglhm — APPROVED** [review]
Looks awesome. Thank you

**Pull request merged**
